apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dotnet-apps-prod-role-binding
  namespace: dotnet-apps-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
