apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
- aspnet-core-apps-prod-ns.yaml
- aspnet-core-apps-prod-rb.yaml

images:
- name: quay.io/kskels/aspnet-core-app
  newTag: v1.1
namespace: dotnet-apps-prod

replicas:
- name: aspnet-core-app
  count: 3

